SurfaceControl: Prevent crash when surfacecontrol is null
* while surfacecontroll is non-null there were some instances that null value is passed to checkPreconditions

fixes:
java.lang.NullPointerException: Attempt to invoke direct method 'void android.view.SurfaceControl.checkNotReleased()' on a null object reference

Change-Id: I8ce78951326f19cbd753e7f9535a444a607a6c56
Signed-off-by: minaripenguin <minaripenguin@users.noreply.github.com>